### PR TITLE
Edit DVC deps to include cmd run files

### PR DESCRIPTION
**Pull request by wagnerlmichael**
This PR edits the `dvc.yaml` file's deps to be consistent with the [documentation](https://dvc.org/doc/user-guide/how-to/add-deps-or-outs-to-a-stage) by adding the files invoked as deps.

### CODE REVIEW

**Review by dfsnow — CHANGES_REQUESTED** [review]
Same deal for this PR @wagnerlmichael. Let's add the hashed files to the lock file.

**Comment by wagnerlmichael** [comment]
@dfsnow mentioned I should update the hash of the `dvc.lock` file since I added the files themselves in the pipeline stage for the `dvc.yaml` pipeline. Currently there are only 6 stages in the `dvc.lock` file although there are 7 total stages in the `dvc.yaml`. Should we update the `dvc.lock` to incorporate all 7 stages? This is the only way it makes sense for me to add hash data @wrridgeway

**Comment by wagnerlmichael** [comment]
Maybe it isn't super necessary to have all 7 stages included. I'll ping for review to get the ball rolling.

**Review by dfsnow — COMMENTED** [review]
@wagnerlmichael I just merged master into this branch. Can you pull and rehash the deps to catch any changes from the code that got pulled in? Then this should be good to go.

**Comment by wagnerlmichael** [comment]
I actually do think we should run dvc again and hook up the missing file in `dvc.lock`. Does that sound right? @dfsnow

**Comment by dfsnow** [comment]
> I actually do think we should run dvc again and hook up the missing file in `dvc.lock`. Does that sound right? @dfsnow

Yes please @wagnerlmichael

**Pull request merged**
